// Static owner dashboard. Untrusted comments are rendered with textContent only.
export const adminMarkup = `<section id="dashboard" hidden><h2>30-day tester feedback</h2><p id="coverage"></p><div id="cards" class="cards"></div><h3>Usage steps</h3><table><thead><tr><th>Step</th><th>Count</th></tr></thead><tbody id="steps"></tbody></table><h3>Reviewed written feedback</h3><p>Comments were explicitly approved by testers. Do not copy applicant data into this dashboard.</p><div id="comments"></div><button id="export">Download this page as JSON</button><button id="next" hidden>Load next 1,000 records</button><button id="refresh">Refresh</button><button id="logout">End owner session</button><details><summary>Data record details</summary><pre id="data"></pre></details></section>`;
export const adminScript = `let latest=null,offset=0; const labels={session_started:'Sessions started',demo_opened:'Demo opened',generation_started:'Generation started',generation_completed:'Generation completed',generation_failed:'Generation failed',generation_cancelled:'Generation cancelled',job_saved:'Jobs saved',job_imported:'Jobs imported',resume_edited:'Resumes edited',export_downloaded:'Exports downloaded',print_opened:'Print opened'};
function text(tag,value){const node=document.createElement(tag);node.textContent=value;return node}
async function refresh(){const response=await fetch('/api/pilot/admin/export?offset='+offset);const data=await response.json();if(!response.ok){status.textContent=data.error;return}latest=data;document.querySelector('#dashboard').hidden=false;status.textContent='Only opted-in feedback is shown. Generation follows the configured local provider and daily limits.';
const coverage=document.querySelector('#coverage');coverage.textContent='All retained data: 30 days. Coverage '+(data.coverage.first?new Date(data.coverage.first).toLocaleString()+' to '+new Date(data.coverage.last).toLocaleString():'no opted-in data yet')+'. Page '+(Math.floor(offset/1000)+1)+'.';
const cards=document.querySelector('#cards');cards.replaceChildren();for(const [name,value] of [['Consenting testers',data.participants.filter(p=>p.consent===1).length],['Completed generations',data.eventCounts.generation_completed||0],['Generation errors',data.eventCounts.generation_failed||0],['Written feedback',data.feedbackSummary.count],['Average rating',data.feedbackSummary.averageRating===null?'No ratings':Number(data.feedbackSummary.averageRating).toFixed(1)+' / 5']]){const card=text('article','');card.append(text('strong',String(value)),text('p',name));cards.append(card)}
const steps=document.querySelector('#steps');steps.replaceChildren();for(const [name,label] of Object.entries(labels)){const row=text('tr','');row.append(text('td',label),text('td',String(data.eventCounts[name]||0)));steps.append(row)}
const comments=document.querySelector('#comments');comments.replaceChildren();if(!data.feedback.length)comments.append(text('p','No reviewed feedback on this page.'));for(const item of data.feedback){const card=text('article','');card.append(text('h4',item.rating+' / 5 — '+item.goal.replaceAll('_',' ')),text('p','Accuracy: '+item.accuracy.replaceAll('_',' ')+'. Outcome: '+item.outcome.replaceAll('_',' ')+'. '+new Date(item.created_at).toLocaleString()),text('p',item.comment||'(No written comment)'));comments.append(card)}document.querySelector('#data').textContent=JSON.stringify(data,null,2);document.querySelector('#next').hidden=data.nextOffset===null;}
document.querySelector('#refresh').onclick=()=>{offset=0;refresh()};document.querySelector('#next').onclick=()=>{offset=latest.nextOffset;refresh()};document.querySelector('#export').onclick=()=>{if(!latest)return;const url=URL.createObjectURL(new Blob([JSON.stringify(latest,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='resume-foundry-pilot-'+new Date().toISOString().slice(0,10)+'-page-'+(Math.floor(offset/1000)+1)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.querySelector('#logout').onclick=async()=>{await fetch('/api/pilot/admin/logout',{method:'POST'});location.reload()};`;
